name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    environment: Deployment
    env:
      SKIP_DEPLOY: ${{ contains(join(toJson(github.event.commits.*.message)), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: npm install 
        run: npm install  
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: create .env file
        run: |
          echo "MONGODB_URI = ${{ secrets.MONGODB_URI }}" > .env;
          echo "TEST_MONGODB_URI = ${{ secrets.TEST_MONGODB_URI }}" >> .env;
          echo "SECRET = ${{ secrets.SECRET }}" >> .env
      - name: test backend
        run: |
          npm run start-test &
          sleep 5 &&
          npm run test:backend
      - name: e2e tests
        uses: cypress-io/github-action@v4
        with:
          wait-on: http://localhost:3003/
      - name: deploy to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "intense-dusk-75932"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          rollbackonhealthcheckfailed: true
        if: ${{ (github.event_name == 'push') && (env.SKIP_DEPLOY == 'false') }}
    outputs:
      SKIP_DEPLOY: ${{ env.SKIP_DEPLOY }}

  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    environment: Deployment
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@3840ec22ac98e14d981375e3ae2d8d0392964521
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          RELEASE_BRANCHES: main
        if: ${{ (github.event_name == 'push') && (needs.simple_deployment_pipeline.outputs.SKIP_DEPLOY == 'false') }}
